project:
  type: website

website:
  title: "NQCRecipes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Tutorials
        href: tutorials/overview.qmd
      - text: How to contribute
        href: contributing/contributing.qmd
  sidebar: 
    - title: Tutorials
      style: docked
      contents: tutorials
    - title: Contributing
      style: docked
      contents: contributing
    
execute: 
  eval: false
  freeze: true

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    



